### ISSUE TITLE
setup a firebase functions job for mailbox

### ISSUE THREAD

**Issue by sansan88** [project-owlly/cloud#22]
Setup a Job that checks periodicly for new mails. the existing inbox method could be used for this. 
for a first phase, this could be every 15mins. (5760 calls per month)

//https://stackoverflow.com/questions/31260837/how-to-run-a-cron-job-on-every-monday-wednesday-and-friday#31260911
Sample:
/* EVERY 1. of MONTH */
exports.scheduleMonthlyEmail = functions.region("europe-west3").pubsub.schedule('00 08 1 * *')
    .timeZone('Europe/Zurich')
    .onRun((context) => {

Trigger the following endpoint in the job:
- https://europe-west6-project-owlly.cloudfunctions.net/mailbox

**Comment by sansan88** [comment]
@peterpeterparker 
this could be something for you as well?

**Comment by peterpeterparker** [comment]
You mean for the mailbox end point? 

sure as soon as the function do something, right now it just extracts data ;)

**Comment by sansan88** [comment]
Yes I have to add another issue with the idea, what the mailbox endpoint should do :)
