### ISSUE TITLE
feat: E-Mail Validation in Firestore

### ISSUE THREAD

**Issue by sansan88** [project-owlly/cloud#54]
https://stackoverflow.com/questions/56819656/firestore-security-rules-check-if-field-is-a-valid-email-address

 - The validation happens in the firestore > rules.
 - if the e-mail is not valid, the user receives an error-toast-message in the frontend and he can change the e-mail and submit his data again.

**Comment by sansan88** [comment]
Validate on create, if the "key" is a e-mail.

![grafik](https://user-images.githubusercontent.com/2372120/96775738-41127080-13e8-11eb-8cd2-c550b5e6f0cc.png)

**Comment by sansan88** [comment]
@peterpeterparker 
If you have time, it would be something for you! Up to you if you are going to use "Rules" or a firebase function. I think better would be firestore rule.

**Comment by sansan88** [comment]
Additionally, Jonathan will do a "Frontend validation" inside the angular form

**Comment by peterpeterparker** [comment]
1. I don't get "where" you want to implement this rule?

2. Why? I mean what happens if the email is not valid?

**Comment by sansan88** [comment]
1. The validation happens in the firestore > rules.
2. if the e-mail is not valid, the user receives an error-toast-message in the frontend and he can change the e-mail and submit his data again.

**Comment by peterpeterparker** [comment]
But I mean, why? What's the added value to check the email value on the backend side?

In worst case, even if you get a couple of hundred subscribers, you will still be able to notice what emails are not correct when you will send the newsletter, as you will receive "unknow email" msgs back, and be able to clean these manually afterwards.

And even if you don't notice it, so what?

For the user who would lik  to register a simple `<input type="email"/>` validation seems enough to me.

Therefore, at least for prototype, I kind of find it is a waste of time and money to implement backend rules.
