### ISSUE TITLE
feat: Send Welcome Mail

### ISSUE THREAD

**Issue by sansan88** [project-owlly/cloud#55]
Send E-Mail with firebase extension (eg. add entry to the e-mail collection).
For the following two collections (on create), we need a database trigger to send e-mail. 

**Newsletter**
description: Send a welcome to owlly mail, if a user registers for newsletter .
template: "newsletter-welcome"

**Feedback**
description: If he provieds feedback, we would say thank you!
template: "feedback-thank-you"

So we need these two database triggers to create a new entry in the "mail" collection. Additionally we need two "empty" templates as described in issue #53 
can you create two templates with the names given above and simply put the names of the users on it? the collection for templates is named "templates"

The Template will be changed at a later stage with a handlebar template. Manuel is designing a html email template.

Use this issue for handlebar templates.. 
#53

**Comment by sansan88** [comment]
@peterpeterparker 
This issue could be one for you if you have time!
in a very first phase, you can build a simple handlebar template described in issue #53

**Comment by peterpeterparker** [comment]
Are you not using a third party service to send newsletter?
If yes, then just set in the tool that an email should be sent.

**Comment by sansan88** [comment]
No, for the moment, we would not use a third party e-mail  / newsletter service. we claim, to have "all" data in switzerland.

**Comment by peterpeterparker** [comment]
Do you really need this?

I mean on the clean side display an answer to the user like "cool thx" or "cool thx we will give back to you asap" and done.

It's not like they are creating a user account, they just registered themselves for a newsletter or have send a question, displaying a "success" msg on screen seems enough to me. Even ask my self if it is not the common behavior in terms of newsletter (?).

As for #54, I would suggest to spare time and money at least for  now  on  that one.

**Comment by sansan88** [comment]
the deal would be, that we can send out the prototypes and forms or ask them to have a look at github
Prototyp
https://www.figma.com/proto/WJqZQe5tLoDJ0CLU1iQRNQ/PT_var1_v0.1_Komprimierte_Anweisungen_4M?node-id=17%3A2&scaling=min-zoom

Umfrage
https://wluzoohc.paperform.co/

**Comment by sansan88** [comment]
"Error: 68668103665472:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332: "

**Comment by sansan88** [comment]
fixed: 
https://github.com/firebase/extensions/issues/456
