### ISSUE TITLE
error: Connection Timeout

### ISSUE THREAD

**Issue by sansan88** [project-owlly/cloud#58]
Just saw this issue in the logs. any idea? 

mailboxScheduler
{ ConnectionTimeoutError: connection timed out. timeout = 3000 ms at Connection.imapOnError (/workspace/node_modules/imap-simple/lib/imapSimple.js:610:23) at Object.onceWrapper (events.js:286:20) at Connection.emit (events.js:198:13) at Connection.EventEmitter.emit (domain.js:448:20) at Timeout._onTimeout (/workspace/node_modules/imap/lib/Connection.js:141:12) at ontimeout (timers.js:436:11) at tryOnTimeout (timers.js:300:5) at listOnTimeout (timers.js:263:5) at Timer.processTimers (timers.js:223:10) message: 'connection timed out. timeout = 3000 ms', name: 'ConnectionTimeoutError' }

![grafik](https://user-images.githubusercontent.com/2372120/97365990-db6e2a80-18a6-11eb-9227-2eda9bf52068.png)

**Comment by sansan88** [comment]
Issue could be, because I have setup an outlook account for this as well..

**Comment by peterpeterparker** [comment]
What was the issue then?

**Comment by sansan88** [comment]
Too many open connections. one from my outlook polling mails and the firebase functions doing the same.
