### ISSUE TITLE
feat: GET owlly api

### ISSUE THREAD

**Issue by sansan88** [project-owlly/cloud#61]
Enhance getOwlly function with this to provide an API for our owllys :) 

GET /owlly
GET /owlly/:id

This is needed for the "scully" static site generation

**Comment by sansan88** [comment]
@peterpeterparker 
Please check this description and let me know, if you need more information about this! It's basically an easy api for our initiatives, stored under /owlly.
I'm not sure, if we need to adjust the "admin" and initialize method in the firestore functions. we should do this somewhere in a separate .ts file and then import it in the others?

**Comment by peterpeterparker** [comment]
@sansan88 

1. what's the goal of `GET /owlly` ?

2. where is `POST /owlly` is going to be called?

**Comment by sansan88** [comment]
1. for scully, creating routes
2. to create Volksbegehren (initiativen+ Referendum)

**Comment by sansan88** [comment]
NO POST
