### ISSUE TITLE
feat: pass state=owllyId to authurl

### ISSUE THREAD

**Issue by sansan88** [project-owlly/cloud#63]
Change Method from Get to Post? (GetEidAuthUrl)
so we can "hide" the state inside the body of the request.
https://github.com/project-owlly/cloud/blob/master/functions/src/request/oidc/getOIDC.ts

Prototyp: https://www.figma.com/proto/JytQQfL4c12pJanZHzisp0/Prototyp_2_wecollect_wizard?node-id=328%3A0&scaling=scale-down

Additionally, we need to change:
- E-Collect Button https://github.com/project-owlly/e-collecting/issues/49
- Signature Button https://github.com/project-owlly/signature/issues/25

**Comment by peterpeterparker** [comment]
@sansan88 did you cleared how we can call eID and get back an information?

**Comment by sansan88** [comment]
Yes thats working! /return page has all of it

**Comment by sansan88** [comment]
We neeed a post! I can change this.. need it for login anyway

**Comment by peterpeterparker** [comment]
To be honest with you, I don't think "callable" function is a valid reason as it is not a standard.
HttpClient or fetch are and supports post  or get.

**Comment by peterpeterparker** [comment]
We have use `onRequest`for our functions

If I understand the docs, callable work with `onCall`

> The functions.https.onCall trigger automatically deserializes the request body and validates auth tokens.

https://firebase.google.com/docs/functions/callable
