### ISSUE TITLE
feat: change generatePDF to callable???

### ISSUE THREAD

**Issue by sansan88** [project-owlly/cloud#73]
Hi @peterpeterparker 

I'm to stupid to change this..  do you know how I can return a pdf in a callable function?

**Comment by sansan88** [comment]
But I found an answer on SO
https://stackoverflow.com/questions/56972994/pipe-file-read-stream-in-firebase-callable-function
we should not use firebase callable for files..

**Comment by sansan88** [comment]
https://blog.angular-university.io/angular-http/

**Comment by peterpeterparker** [comment]
@sansan88 should we return the Pdf? Shouldn't we save it in the storage and return an uri?

**Comment by sansan88** [comment]
Yes we can..

**Comment by sansan88** [comment]
But I would do a new method for this.. generatePDFFileUrl
