### ISSUE TITLE
pdf metadata producer and creator

### ISSUE THREAD

**Issue by peterpeterparker** [project-owlly/cloud#79]
I checked the source code of [pdfkit](https://github.com/foliojs/pdfkit/blob/326350b7f958ed24730ce809b98dc803d3e14562/lib/document.js#L899) today and noticed that per default metada procuder and creator are set to "PDFKit". We might want to set "Owlly" for our use case.

To be checked.

**Comment by sansan88** [comment]
Yes that would be super cool! Nice, you found it!

**Comment by sansan88** [comment]
@peterpeterparker 
can you implement this if you find time? for me we should do this!

**Comment by sansan88** [comment]
do you kow what this security info is all about?
    // Initialize security settings
    this._security = PDFSecurity.create(this, options);
